name: real-time-radar
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.9.23
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - colorama==0.4.6
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.56.0
      - importlib-resources==6.5.2
      - kiwisolver==1.4.4
      - llvmlite==0.39.1
      - matplotlib==3.7.1
      - numba==0.56.4
      - numpy==1.23.5
      - opencv-python==4.8.1.78
      - packaging==24.2
      - pillow==11.1.0
      - psutil==5.9.5
      - pyfftw==0.13.1
      - pyparsing==3.2.1
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - pyqtgraph==0.13.3
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - scipy==1.11.1
      - six==1.17.0
      - tqdm==4.67.1
      - zipp==3.23.0
